### ISSUE TITLE
keyboard mode disabled when using the package on web

### ISSUE THREAD

**Issue by matteoberla** [mytooyo/board_datetime_picker#11]
Hi, is it possibile to prevent the keyboard mode activation when on web and other platforms where the keyboard doesn't pop up on screen, while keeping the editing of the fields feature active?

**Comment by mytooyo** [comment]
I see...we'll deal with it so that it can be operated on the web as well.

**Comment by mytooyo** [comment]
I tried to correct it. 
Can you please try the following commit when you have time to see if it matches your request?

```yaml 
board_datetime_picker:
  git:
    url: https://github.com/mytooyo/board_datetime_picker
    ref: db9923f597b830de120ab1b48500a9cb225789c7
```
